---
github_organisation: hcnv
site_domain_name: hcnv.github.io
url: 'http://hcnv.github.io'
tags:
  - code
  - specification
categories:
  - schemas
schema_repos:
  specifications:
    schema_dirs:
      - schemas
    tags:
      - CNV
out_dirnames:
  json: generated/json
  markdown: generated/doc
  examples: generated/examples
webdocs:
  repo: 'hcnv.github.io'
  jekylldir: 'pages/_schemas'
  schemadir: 'schemas'
  web_schemas_rel: "/schemas"
  web_html_rel: "/schemas"
generator_prefix: '+generated__'
schema_disclaimer: |
  <hr/>
  <div id="schema-footer">
  This schema representation is for information and testing purposes.
  </div>
jekyll_excerpt_separator: "<!--more-->"
prefix_expansions:
  orcid: 'https://orcid.org/'
  PMID: 'https://www.ncbi.nlm.nih.gov/pubmed/'
links:
  sb_status_levels: "https://schemablocks.org/about/sb-status-levels.html"
podmd: ''
